# SPDX-FileCopyrightText: 2014 MicroPython & CircuitPython contributors (https://github.com/adafruit/circuitpython/graphs/contributors)
#
# SPDX-License-Identifier: MIT

name: Build CI

on:
  push:
  pull_request:
  release:
    types: [published]
  check_suite:
    types: [rerequested]

jobs:
  scheduler-xtensa:
    runs-on: ubuntu-20.04
    steps:
    - name: Set up Cache
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}-test
    - name: Setup repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Docker Build
      uses: docker/build-push-action@v2
      with:
        push: false
        context: .
    # Temp fix
    # https://github.com/docker/build-push-action/issues/252
    # https://github.com/moby/buildkit/issues/1896
    - name: Move cache
      run: |
        rm -rf /tmp/.buildx-cache
        mv /tmp/.buildx-cache-new /tmp/.buildx-cache

  build-xtensa:
    runs-on: ubuntu-20.04
    needs: scheduler-xtensa
    strategy:
      fail-fast: false
      matrix:
        board:
        - "adafruit_feather_esp32s2_nopsram"
        - "adafruit_feather_esp32s2_tftback_nopsram"
        - "adafruit_funhouse"
        - "adafruit_magtag_2.9_grayscale"
        - "adafruit_metro_esp32s2"
        - "artisense_rd00"
        - "atmegazero_esp32s2"
        - "electroniccats_bastwifi"
        - "espressif_kaluga_1"
        - "espressif_kaluga_1.3"
        - "espressif_saola_1_wroom"
        - "espressif_saola_1_wrover"
        - "franzininho_wifi_wroom"
        - "franzininho_wifi_wrover"
        - "lilygo_ttgo_t8_s2_st7789"
        - "microdev_micro_s2"
        - "muselab_nanoesp32_s2_wroom"
        - "muselab_nanoesp32_s2_wrover"
        - "targett_module_clip_wroom"
        - "targett_module_clip_wrover"
        - "unexpectedmaker_feathers2"
        - "unexpectedmaker_feathers2_prerelease"
        - "unexpectedmaker_tinys2"

    steps:
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Cache build environment
      id: cache-build-env
      uses: actions/cache@v2
      with:
        path: |
          ~/.cache/pip/
          /home/runner/work/circuitpython/
        key: ${{ github.run_id }}-${{ github.run_number }}
    - name: Check cache-miss
      if: steps.cache-build-env.outputs.cache-hit != 'true'
      run: |
        echo "Cache-miss spotted. Aborting..."
        exit 1
    - name: Versions
      run: |
        source $IDF_PATH/export.sh
        gcc --version
        xtensa-esp32s2-elf-gcc --version
        python3 --version
        ninja --version
        cmake --version
    - name: Setup build failure matcher
      run: echo "::add-matcher::$GITHUB_WORKSPACE/.github/workflows/match-build-fail.json"
    - name: build
      run: |
        source $IDF_PATH/export.sh
        python3 -u build_release_files.py
      working-directory: tools
      shell: bash
      env:
        IDF_PATH: ${{ github.workspace }}/ports/esp32s2/esp-idf
        IDF_TOOLS_PATH: ${{ github.workspace }}/.idf_tools
        BOARDS: ${{ matrix.board }}
    - uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.board }}
        path: bin/${{ matrix.board }}
    - name: Upload to S3
      run: "[ -z \"$AWS_ACCESS_KEY_ID\" ] || aws s3 cp bin/ s3://adafruit-circuit-python/bin/ --recursive --no-progress --region us-east-1"
      env:
        AWS_PAGER: ''
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      if: github.event_name == 'push' || (github.event_name == 'release' && (github.event.action == 'published' || github.event.action == 'rerequested'))
